import pandas as pd

# df = pd.read_csv('/Users/minghaotao/Desktop/GS_Late/CIS_5810_-_Spring_2023_Spring_2023_grades.csv')
#
# print(df.columns)

course_url = {
    '5500': 'https://gradescope.com/courses/{Gradescope course ID}/gradebook.csv',

}

canvas_id_map = {"5500": {Canvas Course ID},
    
                 }

assignment_map = {"5500": {"Homework 1 - Submission Time": 10711032, "Homework 2 - Submission Time": 10711033,
                           "Homework 3 - Submission Time": 10711034, "Homework 4 - Submission Time": 10711035,
                           "Homework 5 - Submission Time": 10711036, "Homework 6 - Submission Time": 10711037},

                  "5810": {"Homework 1 - Convolution - Submission Time": 10715236,
                           "Homework 2 - Canny Edge Detection - Submission Time": 10715238,
                           "Homework 3 - Optical Flow - Submission Time": 10715239,
                           "Project 1 - Dolly Zoom - Submission Time": 10715261,
                           "Project 2 - Canny Edge Detection - Submission Time": 10715262,
                           "Project 3 - Laplacian Blending - Submission Time": 10715263,
                           "Project 4 - Homography Estimation - Submission Time": 10715264,
                           "Project 5 - Image Morphing - Submission Time": 10715265,
                           "Project 6 - Poisson Image Editing - Submission Time": 10715266,
                           "Project 7 - Linear Regression - Submission Time": 10715267,
                           "Project 8 - Linear Perceptron - Submission Time": 10715268,
                           "Project 9 - Classification Part 1 - Submission Time": 10715269,
                           "Project 9 - Classification Part 2 - Submission Time": 10804709,
                           },

                  "5930": {
                      "Assignment 03: Transistors to Logic - Submission Time": 10710421,
                      "Assignment 04: Sequential Logic & Memory - Submission Time": 10710422,
                      "Assignment 05: Datapath - Submission Time": 10710423,
                      "Assignment 06: LC4 ISA - Submission Time": 10710426,
                      "Assignment 06: LC4 ISA Control Signal Table Autograder - Submission Time": 10710425,
                      "Assignment 07: LC4 Assembly Programming (Gradescope) - Submission Time": 10710428,
                      "Assignment 08: LC4 Assembly and I/O (Gradescope) - Submission Time": 10710430,
                      "Assignment 09: Connecting C to Assembly and I/O Devices - Submission Time": 10710432,
                      "Assignment 10: Intro to C and its Development Environment - Submission Time": 10710416,
                      "Assignment 12: File I/O, Making the LC4 Assembler - Submission Time": 10710419,
                  },

                  "5920": {"Module 1 Assignment - Submission Time": 123, "Module 2 Assignment - Submission Time": 234,
                           "Module 3 Assignment - Submission Time": 456, "Module 4 Assignment - Submission Time": 456,
                           "Module 5 Assignment - Submission Time": 567, "Module 6 Assignment - Submission Time": 786,
                           "Module 7 Assignment - Submission Time": 890, "Module 8 Assignment - Submission Time": 897,
                           "Module 9 Assignment - Submission Time": 345,
                           "Module 10 Assignment - Submission Time": 234, "Module 11 Assignment - Submission Time": 456,
                           "Module 12 Assignment - Submission Time": 345,
                           "Module 13 Assignment - Submission Time": 456,
                           "Module 14 Assignment - Submission Time": 789},
                  "5960": {"Module 1-2 Homework Assignment - Submission Time": 11107794,
                           "Module 3-4 Homework Assignment - Submission Time": 11107801,
                           "Module 5-6 Homework Assignment - Submission Time": 11107804,
                           "Module 7-8 Homework Assignment - Submission Time": 11107807,
                           "Module 9-10 Homework Assignment - Submission Time": 11107810,
                           "Module 11-12 Homework Assignment - Submission Time": 11107792,
                           "Module 13 Homework Assignment - Submission Time": 11107796},
                  }

filters = {"5500": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Homework 1 - Submission Time",
                    "Homework 1 - Lateness (H:M:S)",
                    "Homework 2 - Submission Time",
                    "Homework 2 - Lateness (H:M:S)",
                    "Homework 3 - Submission Time",
                    "Homework 3 - Lateness (H:M:S)",
                    "Homework 4 - Submission Time",
                    "Homework 4 - Lateness (H:M:S)",
                    "Homework 5 - Submission Time",
                    "Homework 5 - Lateness (H:M:S)",
                    "Homework 6 - Submission Time",
                    "Homework 6 - Lateness (H:M:S)"],

           "5810": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    'Homework 1 - Convolution - Submission Time',
                    'Homework 1 - Convolution - Lateness (H:M:S)',
                    'Homework 2 - Canny Edge Detection - Submission Time',
                    'Homework 2 - Canny Edge Detection - Lateness (H:M:S)',
                    'Homework 3 - Optical Flow - Submission Time',
                    'Homework 3 - Optical Flow - Lateness (H:M:S)',
                    "Project 1 - Dolly Zoom - Submission Time",
                    "Project 1 - Dolly Zoom - Lateness (H:M:S)",
                    'Project 2 - Canny Edge Detection - Submission Time',
                    'Project 2 - Canny Edge Detection - Lateness (H:M:S)',
                    'Project 3 - Laplacian Blending - Submission Time',
                    'Project 3 - Laplacian Blending - Lateness (H:M:S)',
                    'Project 4 - Homography Estimation - Submission Time',
                    'Project 4 - Homography Estimation - Lateness (H:M:S)',
                    'Project 5 - Image Morphing - Submission Time',
                    'Project 5 - Image Morphing - Lateness (H:M:S)',
                    'Project 6 - Poisson Image Editing - Submission Time',
                    'Project 6 - Poisson Image Editing - Lateness (H:M:S)',
                    'Project 7 - Linear Regression - Submission Time',
                    'Project 7 - Linear Regression - Lateness (H:M:S)',
                    'Project 8 - Linear Perceptron - Submission Time',
                    'Project 8 - Linear Perceptron - Lateness (H:M:S)',
                    'Project 9 - Classification Part 1 - Submission Time',
                    'Project 9 - Classification Part 1 - Lateness (H:M:S)',
                    'Project 9 - Classification Part 2 - Submission Time',
                    'Project 9 - Classification Part 2 - Lateness (H:M:S)',

                    ],

           "5930": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Assignment 03: Transistors to Logic - Submission Time",
                    "Assignment 03: Transistors to Logic - Lateness (H:M:S)",
                    "Assignment 04: Sequential Logic & Memory - Submission Time",
                    "Assignment 04: Sequential Logic & Memory - Lateness (H:M:S)",
                    "Assignment 05: Datapath - Submission Time",
                    "Assignment 05: Datapath - Lateness (H:M:S)",
                    "Assignment 06: LC4 ISA - Submission Time", "Assignment 06: LC4 ISA - Lateness (H:M:S)",
                    "Assignment 06: LC4 ISA Control Signal Table Autograder - Submission Time",
                    "Assignment 06: LC4 ISA Control Signal Table Autograder - Lateness (H:M:S)",
                    "Assignment 07: LC4 Assembly Programming (Gradescope) - Submission Time",
                    "Assignment 07: LC4 Assembly Programming (Gradescope) - Lateness (H:M:S)",
                    "Assignment 08: LC4 Assembly and I/O (Gradescope) - Submission Time",
                    "Assignment 08: LC4 Assembly and I/O (Gradescope) - Lateness (H:M:S)",
                    "Assignment 09: Connecting C to Assembly and I/O Devices - Submission Time",
                    "Assignment 09: Connecting C to Assembly and I/O Devices - Lateness (H:M:S)",
                    "Assignment 10: Intro to C and its Development Environment - Submission Time",
                    "Assignment 10: Intro to C and its Development Environment - Lateness (H:M:S)",
                    "Assignment 12: File I/O, Making the LC4 Assembler - Submission Time",
                    "Assignment 12: File I/O, Making the LC4 Assembler - Lateness (H:M:S)"],
           "5920": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    "Module 1 Assignment - Submission Time", 'Module 1 Assignment - Lateness (H:M:S)',
                    'Module 2 Assignment - Submission Time', 'Module 2 Assignment - Lateness (H:M:S)',
                    'Module 3 Assignment - Submission Time', 'Module 3 Assignment - Lateness (H:M:S)',
                    'Module 4 Assignment - Submission Time', 'Module 4 Assignment - Lateness (H:M:S)',
                    'Module 5 Assignment - Submission Time', 'Module 5 Assignment - Lateness (H:M:S)',
                    'Module 6 Assignment - Submission Time', 'Module 6 Assignment - Lateness (H:M:S)',
                    'Module 7 Assignment - Submission Time', 'Module 7 Assignment - Lateness (H:M:S)',
                    'Module 8 Assignment - Submission Time', 'Module 8 Assignment - Lateness (H:M:S)',
                    'Module 9 Assignment - Submission Time', 'Module 9 Assignment - Lateness (H:M:S)',
                    'Module 10 Assignment - Submission Time', 'Module 10 Assignment - Lateness (H:M:S)',
                    'Module 11 Assignment - Submission Time', 'Module 11 Assignment - Lateness (H:M:S)',
                    'Module 12 Assignment - Submission Time', 'Module 12 Assignment - Lateness (H:M:S)',
                    'Module 13 Assignment - Submission Time', 'Module 13 Assignment - Lateness (H:M:S)',
                    'Module 14 Assignment - Submission Time', 'Module 14 Assignment - Lateness (H:M:S)',

                    ],
           "5960": ["First Name", "Last Name", "Name", "SID", "Email", "Sections",
                    'Module 1-2 Homework Assignment - Submission Time',
                    'Module 1-2 Homework Assignment - Lateness (H:M:S)',
                    'Module 3-4 Homework Assignment - Submission Time',
                    'Module 3-4 Homework Assignment - Lateness (H:M:S)',
                    'Module 5-6 Homework Assignment - Submission Time',
                    'Module 5-6 Homework Assignment - Lateness (H:M:S)',
                    'Module 7-8 Homework Assignment - Submission Time',
                    'Module 7-8 Homework Assignment - Lateness (H:M:S)',
                    'Module 9-10 Homework Assignment - Submission Time',
                    'Module 9-10 Homework Assignment - Lateness (H:M:S)',
                    'Module 11-12 Homework Assignment - Submission Time',
                    'Module 11-12 Homework Assignment - Lateness (H:M:S)',
                    'Module 13-14 Homework Assignment - Submission Time',
                    'Module 13 Homework Assignment - Lateness (H:M:S)'],

           }
